site_name: Roadmap Android Developer (Java)
theme:
  name: material


nav:
  - Home: index.md
  - Dasar Java:
    - Sintaks Dasar Java: 01-Dasar-Java/01-sintaks-dasar-java.md
    - Operator: 01-Dasar-Java/02-operator.md
    - Tipe Data: 01-Dasar-Java/02-tipe-data.md
    - Variabel: 01-Dasar-Java/02-variabel.md
    - If-Else: 01-Dasar-Java/03-if-else.md
    - Looping: 01-Dasar-Java/03-looping.md
    - Switch-Case: 01-Dasar-Java/03-switch-case.md
    - Functions: 01-Dasar-Java/04-functions.md
    - Method: 01-Dasar-Java/04-method.md
    - Class: 01-Dasar-Java/05-class.md
    - Object: 01-Dasar-Java/05-object.md
    - Abstraction: 01-Dasar-Java/06-abstraction-oop.md
    - Encapsulation: 01-Dasar-Java/06-encapsulation.md
    - Inheritance: 01-Dasar-Java/06-inheritance.md
    - Polymorphism: 01-Dasar-Java/06-polymorphism.md
    - Exception Handling: 01-Dasar-Java/07-exception-handling.md
    - Collection Framework: 01-Dasar-Java/08-collection-framework.md
    - Threading dan Concurrency dalam Java: 01-Dasar-Java/09-threading-dan-concurrency-dalam-java.md
    - Tools Bantu: 01-Dasar-Java/09-tools-bantu.md



markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
